version: '3'
services:
  mqtt:
    image: "ansi/mosquitto"
    restart: always
    ports:
      - "1883:1883"
  mqtt-gateway:
    build: ./mqtt-gateway
    restart: always
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    links:
      - mqtt:mosquitto
  mqtt-cctv:
    build: ./mqtt-cctv
    restart: always
    links:
      - mqtt:mosquitto
    volumes:
      - "/data/cctv/events:/cctv/events"
